# Generated by Django 3.2 on 2021-10-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20211030_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='energy',
            field=models.IntegerField(default=0),
        ),
    ]
