# Generated by Django 3.2 on 2021-10-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_product_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbohydrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
